@file:Suppress("SpellCheckingInspection")

object Dependencies {

    const val androidXConstraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.Dependencies.androidXConstraintLayout}"
    const val androidXFragmentKtx = "androidx.fragment:fragment-ktx:${Versions.Dependencies.androidXFragment}"
    const val androidXLegacySupportV4 = "androidx.legacy:legacy-support-v4:${Versions.Dependencies.androidXLegacySupportV4}"
    const val androidXLifecycleLiveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.Dependencies.androidXLifecycle}"
    const val androidXLifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.Dependencies.androidXLifecycle}"
    const val androidXLifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.Dependencies.androidXLifecycle}"
    const val androidXNavigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:${Versions.Dependencies.androidXNavigation}"
    const val androidXNavigationUIKtx = "androidx.navigation:navigation-ui-ktx:${Versions.Dependencies.androidXNavigation}"
    const val androidXPreferenceKtx = "androidx.preference:preference-ktx:${Versions.Dependencies.androidXPreference}"
    const val androidXRecyclerView = "androidx.recyclerview:recyclerview:${Versions.Dependencies.androidXRecyclerView}"
    const val firebaseBoM = "com.google.firebase:firebase-bom:${Versions.Dependencies.firebaseBoM}"
    const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
    const val firebaseCrashlytics = "com.google.firebase:firebase-crashlytics-ktx"
    const val firebasePerf = "com.google.firebase:firebase-perf-ktx"
    const val geoCoordinatesConversion = "com.github.Berico-Technologies:Geo-Coordinate-Conversion-Java:${Versions.Dependencies.geoCoordinatesConversion}"
    const val guava = "com.google.guava:guava:${Versions.Dependencies.guava}"
    const val kotestAssertionsCoreJvm = "io.kotest:kotest-assertions-core-jvm:${Versions.Dependencies.kotest}"
    const val kotestPropertyJvm = "io.kotest:kotest-property-jvm:${Versions.Dependencies.kotest}"
    const val kotestRunnerJUnit5 = "io.kotest:kotest-runner-junit5-jvm:${Versions.Dependencies.kotest}"
    const val kotlinxCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.Dependencies.kotlinxCoroutines}"
    const val kotlinxCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.Dependencies.kotlinxCoroutines}"
    const val loaderView = "com.elyeproj.libraries:loaderviewlibrary:${Versions.Dependencies.loaderView}"
    const val material = "com.google.android.material:material:${Versions.Dependencies.material}"
    const val pageIndicatorView = "com.romandanylyk:pageindicatorview:${Versions.Dependencies.pageIndicatorView}"
    const val playServicesLocation = "com.google.android.gms:play-services-location:${Versions.Dependencies.playServicesLocation}"
    const val sunriseSunset = "ca.rmen:lib-sunrise-sunset:${Versions.Dependencies.sunriseSunset}"
    const val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.Dependencies.threeTenAbp}"
    const val timber = "com.jakewharton.timber:timber:${Versions.Dependencies.timber}"
}