@file:Suppress("SpellCheckingInspection")

object Dependencies {

    const val androidXConstraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.Dependencies.androidXConstraintLayout}"
    const val androidXFragmentKtx = "androidx.fragment:fragment-ktx:${Versions.Dependencies.androidXFragment}"
    const val androidXLegacySupportV4 = "androidx.legacy:legacy-support-v4:${Versions.Dependencies.androidXLegacySupportV4}"
    const val androidXLifecycleCommonJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.Dependencies.androidXLifecycle}"
    const val androidXLifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.Dependencies.androidXLifecycle}"
    const val androidXNavigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:${Versions.Dependencies.androidXNavigation}"
    const val androidXNavigationUIKtx = "androidx.navigation:navigation-ui-ktx:${Versions.Dependencies.androidXNavigation}"
    const val androidXPreferenceKtx = "androidx.preference:preference-ktx:${Versions.Dependencies.androidXPreference}"
    const val androidXRecyclerView = "androidx.recyclerview:recyclerview:${Versions.Dependencies.androidXRecyclerView}"
    const val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.Dependencies.crashlytics}"
    const val firebaseCore = "com.google.firebase:firebase-core:${Versions.Dependencies.firebaseCore}"
    const val firebasePerf = "com.google.firebase:firebase-perf:${Versions.Dependencies.firebasePerf}"
    const val geoCoordinatesConversion = "com.github.Berico-Technologies:Geo-Coordinate-Conversion-Java:${Versions.Dependencies.geoCoordinatesConversion}"
    const val kotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.Dependencies.kotlin}"
    const val kotlinStdLibJdk8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.Dependencies.kotlin}"
    const val loaderView = "com.elyeproj.libraries:loaderviewlibrary:${Versions.Dependencies.loaderView}"
    const val material = "com.google.android.material:material:${Versions.Dependencies.material}"
    const val pageIndicatorView = "com.romandanylyk:pageindicatorview:${Versions.Dependencies.pageIndicatorView}"
    const val playServicesLocation = "com.google.android.gms:play-services-location:${Versions.Dependencies.playServicesLocation}"
    const val spekDsl = "org.spekframework.spek2:spek-dsl-jvm:${Versions.Dependencies.spek}"
    const val spekRunnerJUnit5 = "org.spekframework.spek2:spek-runner-junit5:${Versions.Dependencies.spek}"
    const val sunriseSunset = "ca.rmen:lib-sunrise-sunset:${Versions.Dependencies.sunriseSunset}"
    const val threeTenAbp = "com.jakewharton.threetenabp:threetenabp:${Versions.Dependencies.threeTenAbp}"
    const val timber = "com.jakewharton.timber:timber:${Versions.Dependencies.timber}"
    const val truth = "com.google.truth:truth:${Versions.Dependencies.truth}"
}