name: Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v5

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v4

      - name: 'Set up the Android SDK'
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: 'Run unit tests'
        run: >-
          ./gradlew test koverXmlReport

      - name: 'Upload coverage report to Codecov'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
